myproject/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, hello_world

app_name="accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path('login/', LoginView.as_view(template_name=f'{app_name}/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

myproject/commentapp/urls.py
from .views import CommentCreateView, CommentDeleteView
from django.urls import path

app_name = 'commentapp'
urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/commentapp/models.py
from django.db import models
from articleapp.models import Article
from django.contrib.auth.models import User

# Create your models here.
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.SET_NULL, null=True,
                                related_name='comment')
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                related_name='comment')
    content = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now=True)

myproject/commentapp/views.py
from .decorators import comment_ownership_required
from django.views.generic.edit import DeleteView
from articleapp.models import Article
from django.views.generic import CreateView
from django.urls import reverse
from .models import Comment
from .form import CommeentCreationForm
from django.utils.decorators import method_decorator

# Create your views here.
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommeentCreationForm
    template_name = 'commentapp/create.html'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.article = Article.objects.get(pk=self.request.POST['article_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk})

@method_decorator(comment_ownership_required, 'get')
@method_decorator(comment_ownership_required, 'post')
class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    template_name = 'commentapp/delete.html'

    def get_success_url(self) -> str:
        return reverse('articleapp:detail', kwargs={'pk': self.object.article.pk})

myproject/commentapp/templates/commentapp/create.html
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class='mb-4'>
        <h4>Comment Create</h4>
    </div>
    <form action="{% url 'commentapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% if user.is_authenticated %}
        <input type="submit" class="btn btn-primary col-6 mt-3">
        {% else %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="btn btn-primary col-6 mt-3">
            login
        </a>
        {% endif %}
        <input type="hidden" name="article_pk" value="{{ article.pk }}">

    </form>

</div>

{% endblock %}

myproject/commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class='mb-4'>
        <h4>Delete Comment {{ target_comment.content }} </h4>
    </div>
    <form action="{% url 'commentapp:delete' pk=target_comment.pk%}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger col">
    </form>

</div>

{% endblock %}

myproject/commentapp/templates/commentapp/detail.html
<div
    style="border: 1px solid; text-align: left; padding: 4%; margin: 1rem 0; border-radius: 1rem; border-color: rgb(180, 86, 86);">
    <div>
        <strong>
            {{ comment.writer.profile.nickname }}
        </strong>
        &nbsp;
        {{ comment.created_at }}
    </div>
    <div>
        {{ comment.content }}
    </div>

    <div>
    {% if comment.writer == user %}
        <a href="{% url 'commentapp:delete' pk=comment.pk %}">
            Delete
        </a>
    {% endif %}
    </div>
</div>