myproject/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, hello_world

app_name="accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path('login/', LoginView.as_view(template_name=f'{app_name}/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/profileapp/urls.py
from .views import ProfileCreateView, ProfileUpdateView
from django.urls import path

app_name="profileapp"

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('create/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

myproject/accountapp/models.py
from django.db import models

class HelloWorld2(models.Model):
    text = models.CharField(max_length=255, null=False)

myproject/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

myproject/accountapp/views.py
from django.views.generic.edit import DeleteView
from .forms import AccountUpdateForm
from django.http.response import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .decorators import account_ownership_required

from .models import HelloWorld2
from django.shortcuts import render

app_name = "accountapp"
has_ownership = [account_ownership_required, login_required]

# Create your views here.
@login_required
def hello_world(request):
    if request.method == "POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld2()
        new_hello_world.text = temp
        new_hello_world.save()

        return HttpResponseRedirect(reverse(f'{app_name}:hello_world'))
    else:
        hello_world_list = HelloWorld2.objects.all()
        return render(request, 'accountapp/helloworld.html', context={'hello_world_list': hello_world_list})


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy(f"{app_name}:hello_world")
    template_name = f'{app_name}/create.html'
class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = f'{app_name}/detail.html'
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy(f"{app_name}:hello_world")
    template_name = f'{app_name}/update.html'
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy(f"{app_name}:login")
    template_name = f'{app_name}/delete.html'

myproject/accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class='mb-4'>
        <h4>SignUp</h4>
    </div>
    <form action="{% url 'accountapp:create' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>

</div>

{% endblock %}

myproject/accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class='mb-4'>
        <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk%}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger col">
    </form>

</div>

{% endblock %}

myproject/accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

<div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">

        
        {% if target_user.profile %}
        <img src="{{ target_user.profile.image.url }}" alt="{{ target_user.profile.image.url }}" 
            style="height: 10rem; width: 10rem; border-radius: 10rem; margin-bottom: 2rem">
        <h2>
            {{ target_user.profile.nickname }}

            {% if target_user == user %}
            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                edit
            </a>
            {% endif %}

        </h2>

        <h6 style="margin-bottom: 3rem;">
            {{ target_user.profile.message }}
        </h6>
        {% else %}
            {% if target_user == user %}
            <a href="{% url 'profileapp:create' %}">
                <h4>
                    Create Profile
                </h4>
            </a>
            {% else %}
            <h2>
                닉네임 미설정
            </h2>
            {% endif %}
        {% endif %}

        {% if target_user == user %}
        <a href="{% url 'accountapp:update' pk=user.pk %}">
            <p>
                Change Info
            </p>
        </a>
        <a href="{% url 'accountapp:delete' pk=user.pk %}">
            <p>
                Quit
            </p>
        </a>
        {% endif %}
    </div>
</div>

{% endblock %}

myproject/accountapp/templates/accountapp/helloworld.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family: 'Lobster', cursive;">Hello World List</h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            
            <div>
                <input type="text" name="hello_world_input">
            </div>

            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>


        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
        <h4>
            {{ hello_world.text }}
        </h4>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

myproject/accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div>
        <h4>Login</h4>
    </div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-4">
        </form>
    </div>
</div>

{% endblock %}

myproject/accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class='mb-4'>
        <h4>Update Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>

</div>

{% endblock %}