myproject/accountapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from .views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, hello_world

app_name="accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name="hello_world"),

    path('login/', LoginView.as_view(template_name=f'{app_name}/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

myproject/articleapp/urls.py
from .views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView
from django.urls import path

app_name = 'articleapp'
urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(),name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(),name='delete'),
]

myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body>

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>

</html>

myproject/templates/footer.html
<div class="footer">
    <div class="footer_content">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>

    <div class="footer_logo">
        <h6>Pragmatic</h6>
    </div>
</div>

myproject/templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- BOOTSTRAP LINK -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- GOOGLE FONT LINK  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <title>Django practice</title>
</head>

myproject/templates/header.html
<div class="header">
    <div class="header_logo">
        <h1>Django practice</h1>
    </div>
    <div>
        <span>
            <a href="{% url 'articleapp:list' %}">
                <span>list</span>
            </a>
        </span>
        <span>nav2</span>
        <span>nav3</span>

        {% if not user.is_authenticated %}
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
            <span>Login</span>
        </a>
        <a href="{% url 'accountapp:create' %}?next={{ request.path }}">
            <span>Create</span>
        </a>
        {% else %}
        <a href="{% url 'accountapp:detail' pk=user.pk %}">
            <span>MyPage</span>
        </a>
        <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            <span>logout</span>
        </a>
        {% endif %}

    </div>
</div>